CMAKE_MINIMUM_REQUIRED(VERSION 3.5.0)


PROJECT(ex_ecc)


SET(SIMW_LIB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/..)
INCLUDE(${SIMW_LIB_DIR}/simw_lib.cmake)

IF(SSS_HAVE_SE05X_AUTH_NONE)
ADD_EXECUTABLE(${PROJECT_NAME} ${SIMW_SE_SOURCES}  ../sss/ex/ecc/ex_sss_ecc.c)
ELSE()
ADD_EXECUTABLE(${PROJECT_NAME}  ${SIMW_SE_SOURCES} ${SIMW_SE_AUTH_SOURCES} ../sss/ex/ecc/ex_sss_ecc.c)
ENDIF()

SIMW_LINK_HOSTCRYPTO(${PROJECT_NAME})

TARGET_INCLUDE_DIRECTORIES(
    ${PROJECT_NAME}
    PUBLIC
        ${SIMW_INC_DIR}
)

ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)