#
# Copyright 2026 NXP
# SPDX-License-Identifier: BSD-3-Clause

# This file is used to set configs or override default configurations for  the example.

# Enable I2C
CONFIG_I2C=y

# Adjust memory configs as needed
CONFIG_MAIN_STACK_SIZE=16384
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_CHIP_TASK_STACK_SIZE=13312